name: Myntra Product ID

on:
  workflow_dispatch:
    inputs:
      product_id:
        description: 'Product ID'
        required: true
        default: "19818628"
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          run: | 
                cd Cypress_Project
                npm start
